openapi: 3.0.3
info:
  title: Function Storage API
  version: 1.0.0
  description: |
    Единый унифицированный контракт API для работы с табулированными функциями.
    Поддерживает:
      - операции CRUD и поиск по владельцу/типу;
      - арифметические операции над функциями (сложение, вычитание, умножение, деление);
      - численное дифференцирование табулированных функций;
      - импорт/экспорт в текстовом и бинарном формате;
      - сериализацию/десериализацию функций.
servers:
  - url: http://localhost:8080/api
    description: |
      Local development (manual: Tomcat, framework: Spring Boot)

security:
  - BasicAuth: []

paths:
  /functions:
    post:
      summary: Создать новую табулированную функцию
      tags: [Functions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCreateRequest'
      responses:
        '201':
          description: Функция создана
          headers:
            Location:
              schema:
                type: string
                example: /api/functions/123
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'

  /functions/{id}:
    get:
      summary: Получить функцию по ID (только владельцу)
      tags: [Functions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Функция найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Функция не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Обновить имя и/или данные функции (только владельцу)
      tags: [Functions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionUpdateRequest'
      responses:
        '200':
          description: Функция обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Удалить функцию (только владельцу)
      tags: [Functions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешно удалено
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/owner/{ownerId}:
    get:
      summary: Получить все функции пользователя
      tags: [Functions]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список функций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/owner/{ownerId}/type/{typeId}:
    get:
      summary: Получить функции пользователя по типу
      tags: [Functions]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: typeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список функций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/{id}/operations/binary:
    post:
      summary: Выполнить бинарную операцию над двумя функциями
      description: |
        Выполняет одну из операций (+, -, *, /) между функцией `id` и второй функцией `secondFunctionId`.
        Результат может быть сохранён как новая функция или возвращён только в ответе (в зависимости от политики сервера).
      tags: [Operations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BinaryOperationRequest'
      responses:
        '200':
          description: Операция успешно выполнена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Некорректные входные данные или несовместимые функции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Одна из функций не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/{id}/derive:
    post:
      summary: Вычислить производную табулированной функции
      description: |
        Вычисляет n‑ую производную (по умолчанию первую) табулированной функции с использованием численного дифференцирования.
      tags: [Operations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DerivativeRequest'
      responses:
        '200':
          description: Производная успешно вычислена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '404':
          description: Функция не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/import/text:
    post:
      summary: Импорт табулированной функции из текстового формата
      description: |
        Импортирует функцию из текстового представления:
        первая строка — количество точек, далее по одной точке на строку в формате "x y".
        Формат соответствует реализации `FunctionsIO.writeTabulatedFunction(BufferedWriter, TabulatedFunction)`.
      tags: [IO]
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: |
                3
                0.0 0.0
                1.0 1.0
                2.0 4.0
      responses:
        '201':
          description: Функция успешно импортирована
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Ошибка формата входных данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/import/binary:
    post:
      summary: Импорт табулированной функции из бинарного формата
      description: |
        Импортирует функцию из бинарного формата:
        сначала 4‑байтовое целое count, затем пары double (x, y) для каждой точки.
        Формат соответствует реализации `FunctionsIO.writeTabulatedFunction(BufferedOutputStream, TabulatedFunction)`.
      tags: [IO]
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: Функция успешно импортирована
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Ошибка формата входных данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/{id}/export/text:
    get:
      summary: Экспорт табулированной функции в текстовом формате
      description: |
        Экспортирует функцию в текстовом формате, совместимом с `FunctionsIO.readTabulatedFunction(BufferedReader, TabulatedFunctionFactory)`.
      tags: [IO]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Текстовое представление функции
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Функция не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/{id}/export/binary:
    get:
      summary: Экспорт табулированной функции в бинарном формате
      description: |
        Экспортирует функцию в бинарном формате, совместимом с `FunctionsIO.readTabulatedFunction(BufferedInputStream, TabulatedFunctionFactory)`.
      tags: [IO]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Бинарное представление функции
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Функция не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/{id}/export/serialized:
    get:
      summary: Сериализованное представление функции (Java Object Serialization)
      description: |
        Возвращает функцию в виде байтов, полученных через `FunctionsIO.serialize(BufferedOutputStream, TabulatedFunction)`.
        Формат предназначен для межсервисного взаимодействия на Java и не является человекочитаемым.
      tags: [IO]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Сериализованная функция
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Функция не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    FunctionCreateRequest:
      type: object
      required: [ownerId, typeId, name, serializedData]
      properties:
        ownerId:
          type: integer
          example: 1
        typeId:
          type: integer
          description: ID типа функции (1 = Tabulated, 2 = SIN и т.д.)
          example: 1
        name:
          type: string
          maxLength: 100
          example: "my_quadratic"
        serializedData:
          type: string
          format: byte
          description: Сериализованные точки (x[], y[]) в base64

    FunctionUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          example: "renamed"
        serializedData:
          type: string
          format: byte
          description: Новые точки (если нужно заменить данные)

    FunctionResponse:
      type: object
      properties:
        id:
          type: integer
        ownerId:
          type: integer
        typeId:
          type: integer
        name:
          type: string
        serializedData:
          type: string
          format: byte
        createdAt:
          type: string
          format: date-time

    BinaryOperationRequest:
      type: object
      required: [secondFunctionId, operation]
      properties:
        secondFunctionId:
          type: integer
          description: ID второй функции, над которой выполняется операция
        operation:
          type: string
          description: Тип бинарной операции
          enum: [ADD, SUB, MULT, DIV]

    DerivativeRequest:
      type: object
      properties:
        order:
          type: integer
          description: Порядок производной (1 — первая, 2 — вторая и т.д.)
          minimum: 1
          default: 1

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "ValidationFailed"
        message:
          type: string
          example: "Поле 'name' не может быть пустым"
        field:
          type: string
          example: "name"
        timestamp:
          type: string
          format: date-time